program_line ::= number _ statement (_ ':' _ statement)*

statement ::=
      assert_statement
    | goto_statement
    | let_statement
    | ...

# ASSERT value [, error-message]
assert_statement ::= 'ASSERT' _ opt_expression_2

# DATA text
data_statement ::= 'DATA' _ repeated_data

repeated_data ::= data (_ ',' data)*

data ::= number | string

# DIM A$(100)
# DIM A$(100,100)
# DIM A$(100,100,100)
dim_statement ::= 'DIM' _ var _ '(' _ expression (_ ',' _ expression (_ ',' _ expression)?)? _ ')' 

# FOR var = start-value TO end-value STEP step-value
for_statement ::= 'FOR' _ var _ '=' _ expression_1 _ 'TO' _ expression_1 _ step?

step ::= 'STEP' _ expression

# GOTO line-number
goto_statement ::= 'GOTO'? _ number

# INPUT [# channel] [prompt ;] var [, var] ...
input_statement ::= 'INPUT' channel prompt _ repeated_var 

# LET var = value
let_statement ::= 'LET'? _ var _ '=' _ expression_1

# LIST start-line-number, end-line-number
list_statement ::= 'LIST' _ opt_expression_2 

# ON value GOTO line-number [, line_number] ...
on_goto_statement ::= 'ON' _ expression1 _ 'GOTO' _ repeated_number

# PRINT print-value
print_statement ::= 'PRINT' channel _ print_expression

# READ var [, var] ...
read_statement ::= 'READ' _ repeated_var

# REM text
rem_statement ::= 'REM' _ text

expression_1 = expression

expression_2 = expression _ ',' _ expression

expression_3 = expression _ ',' _ expression _ ',' _ expression

opt_expression_1 = expression?

opt_expression_2 = (expression (_ ',' _ expression)?)?

opt_expression_3 = (expression (_ ',' _ expression (_ ',' _ expression)?)?)?

expression ::= number | string | var
    | function
    | '(' _ expression _ ')'
    | expression _ op _ expression

print_expression ::= expression
    | print_expression _ ',' (_ expression)?
    | print_expression _ ';' (_ expression)?

function ::=
      len_function
    | max_function
    | min_function
    | ...

# LEN(string-value)
len_function ::= 'LEN' _ '(' _ expression_1 _ ')'

# MAX(value, value)
# MIN(value, value)
max_function ::= 'MAX' _ '(' _ expression_2 _ ')'
min_function ::= 'MIN' _ '(' _ expression_2 ')'

op ::= '<=' | '>=' | '<>' | '<' | '>' | '=' | '+' | '-' | '*' | '/' | '^' | '&' | 'AND' | 'OR'

repeated_number = number (_ ',' _ number)*

repeated_var = var (_ ',' _ var)*

var ::= letter (letter | digit | '_')*

number ::= sign? digit+ ('.' digit*)? ('E' sign? digit+)

string ::= '"' ([^"] | '""')* '"' 

channel ::= _ ('#' number)?

prompt ::= _ (string _ ';')?

letter ::= [A-Z]

digit ::= [0-9]

sign ::= [-+]

_ ::= [ \t]*

text ::= [^\n]

