.import putline_ptr1

; cc65 runtime
.include "zeropage.inc"
.import push1, pusha0, pushax

; sim65 vectors
.import _write, exit 

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __STACKSIZE__

; Export startup address to exehdr module
.export startup

message: .byte "Hello, world", $0A

.segment "STARTUP"

startup:
        cld                     ; Clear decimal flag
        ldx     #$FF
        txs                     ; Initialize the stack to $FF
        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1            ; Set up C stack

        lda     #<message
        sta     ptr1
        lda     #>message
        sta     ptr1+1
        lda     #13
        jsr     putline_ptr1

        ldx     #$00
        lda     #$00
        jmp     exit            ; Return 0 from sim65
