# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# REM

test {
10 REM THIS IS A COMMENT
20 PRINT 1
RUN
} {
1
}

# NEW

test {
10 PRINT 1
NEW
LIST
} {
READY
}

# END and STOP

test {
10 PRINT 1
20 END
30 PRINT 2
RUN
} {
1
}

test {
10 PRINT 1
20 STOP
30 PRINT 2
RUN
} {
1

STOPPED AT 20
}
