# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

test {
PRINT 0
} {
0
}

test {
LET X=5
PRINT X
} {
5
}

test {
PRINT "HELLO, WORLD"
} {
HELLO, WORLD
}

test {
LET PI=3.14159
PRINT "PI=";PI
} {
PI=3.14159
}

# Conatenation

test {
PRINT 1,200,30000
} {
1               200             30000
}

test {
PRINT 1;200;30000
} {
120030000
}

# Alternate '?' syntax

test {
?0
} {
0
}
