dnl SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
dnl
dnl SPDX-License-Identifier: MIT

ifdef(`__C__', `
    define(`def', ``#define $1 $2'')
    define(`hex', `0x$1')
    define(`comment', `//')
    define(`ifdef', ``#ifdef' $1')
    define(`else', ``#else'')
    define(`endif', ``#endif'')
    ', `
    define(`def', ``$1 = $2'')
    define(`hex', `$$1')
    define(`comment', `;')
    define(`ifdef', ``.ifdef' $1')
    define(`else', ``.else'')
    define(`endif', ``.endif'')
    ')

comment Generated from __file__

def(CASE_INSENSITIVE,   hex(80)) comment ORed with terminal token tag in DFA state data

def(TOK_EOL,            hex(00))
def(TOK_COMMA,          hex(01))
def(TOK_SEMI,           hex(02))
def(TOK_LPAREN,         hex(03))
def(TOK_RPAREN,         hex(04))
def(TOK_NOT,            hex(05))
def(TOK_THEN,           hex(06))
def(TOK_TO,             hex(07))
def(TOK_STEP,           hex(08))
def(TOK_COLON,          hex(09))

def(TOK_NON_TERMINAL,   hex(10)) comment Identifies intermediate DFA states
def(TOK_NUM,            hex(11))
def(TOK_SYMBOL,         hex(12))
def(TOK_NAME,           hex(13))
def(TOK_STRING,         hex(14))

def(TOK_ADD,            hex(20))
def(TOK_SUB,            hex(21))
def(TOK_MUL,            hex(22))
def(TOK_DIV,            hex(23))
def(TOK_POW,            hex(24))
def(TOK_CONCAT,         hex(25))
def(TOK_EQ,             hex(26))
def(TOK_LT,             hex(27))
def(TOK_GT,             hex(28))
def(TOK_NE,             hex(29))
def(TOK_LE,             hex(2A))
def(TOK_GE,             hex(2B))
def(TOK_AND,            hex(2C))
def(TOK_OR,             hex(2D))
def(TOK_UNARY_MINUS,    hex(2E)) comment Not generated by lexer but used for operator vector lookup
def(TOK_UNARY_NOT,      hex(2F)) comment Not generated by lexer but used for operator vector lookup

def(TOK_CHANNEL_0,      hex(30))
def(TOK_CHANNEL_1,      hex(31))
def(TOK_CHANNEL_2,      hex(32))
def(TOK_CHANNEL_3,      hex(33))
def(TOK_CHANNEL_4,      hex(34))
def(TOK_CHANNEL_5,      hex(35))
def(TOK_CHANNEL_6,      hex(36))
def(TOK_CHANNEL_7,      hex(37))

def(TOK_PRINT,          hex(40))
def(TOK_ALT_PRINT,      hex(41))
def(TOK_LET,            hex(42))
def(TOK_FOR,            hex(43))
def(TOK_NEXT,           hex(44))
def(TOK_IF,             hex(45))
def(TOK_INPUT,          hex(46))
def(TOK_READ,           hex(47))
def(TOK_ON,             hex(48))
def(TOK_GOTO,           hex(49))
def(TOK_GOSUB,          hex(4A))
def(TOK_LIST,           hex(4B))
def(TOK_REM,            hex(4C))
def(TOK_RESTORE,        hex(4D))
def(TOK_DIM,            hex(4E))
def(TOK_DATA,           hex(4F))
def(TOK_POKE,           hex(50))
def(TOK_DPOKE,          hex(51))
def(TOK_RUN,            hex(52))
def(TOK_STOP,           hex(53))
def(TOK_END,            hex(54))
def(TOK_CONT,           hex(55))
def(TOK_NEW,            hex(56))
def(TOK_CLR,            hex(57))
def(TOK_RETURN,         hex(58))
def(TOK_POP,            hex(59))
def(TOK_GET,            hex(5A))
def(TOK_PUT,            hex(5B))
def(TOK_SAVE,           hex(5C))
def(TOK_LOAD,           hex(5D))

ifdef(`enable_io_channels')
def(TOK_OPEN,           hex(5E))
def(TOK_CLOSE,          hex(5F))
def(TOK_XIO,            hex(60))
endif

def(TOK_LEN,            hex(80))
def(TOK_STR_S,          hex(81))
def(TOK_CHR_S,          hex(82))
def(TOK_ASC,            hex(83))
def(TOK_VAL,            hex(84))
def(TOK_PEEK,           hex(85))
def(TOK_DPEEK,          hex(86))
def(TOK_ADR,            hex(87))
def(TOK_INT,            hex(88))
def(TOK_LOG,            hex(89))
def(TOK_EXP,            hex(8A))
def(TOK_ABS,            hex(8B))
def(TOK_SGN,            hex(8C))
def(TOK_SQR,            hex(8D))
def(TOK_RND,            hex(8E))
def(TOK_LEFT_S,         hex(8F))
def(TOK_RIGHT_S,        hex(90))
def(TOK_USR,            hex(91))
def(TOK_MID_S,          hex(92))
def(TOK_FRE,            hex(93)) 
def(TOK_INKEY_S,        hex(94))
def(TOK_SIN,            hex(95))
def(TOK_COS,            hex(96))
def(TOK_TAN,            hex(97))
def(TOK_ATN,            hex(98))

comment Types

def(TYPE_NUMBER,        hex(00))
def(TYPE_STRING,        hex(01))
def(TYPE_CONTROL,       hex(FF)) comment Only used on stack

comment Expression precedence levels

def(PR_UNARY_OP,        hex(F0))
def(PR_POW,             hex(C0))
def(PR_MUL,             hex(A0))
def(PR_ADD,             hex(80))
def(PR_RELATIONAL,      hex(60))
def(PR_LOGICAL,         hex(40))
def(PR_CLOSE_PAREN,     hex(20))
def(PR_OPEN_PAREN,      hex(00))

comment Program states and error codes

def(PS_RUNNING,                     hex(00))
def(PS_READY,                       hex(01))

def(ERR_STOPPED,                    hex(80))
def(ERR_INTERNAL_ERROR,             hex(81))
def(ERR_OUT_OF_MEMORY,              hex(82))
def(ERR_TYPE_MISMATCH,              hex(83))
def(ERR_CONT_WITHOUT_STOP,          hex(84))
def(ERR_OUT_OF_DATA,                hex(85))
def(ERR_STACK,                      hex(86))
def(ERR_RETURN_WITHOUT_GOSUB,       hex(87))
def(ERR_NEXT_WITHOUT_FOR,           hex(88))
def(ERR_LINE_NOT_FOUND,             hex(89))
def(ERR_OUT_OF_RANGE,               hex(8A))
def(ERR_INVALID_VARIABLE,           hex(8B))
def(ERR_EXISTS,                     hex(8C))
def(ERR_LINE_TOO_LONG,              hex(8D))
def(ERR_EXPRESSION_TOO_COMPLEX,     hex(8E))
def(ERR_FORMAT_ERROR,               hex(8F))
def(ERR_ARITY_MISMATCH,             hex(90))
def(ERR_SYNTAX_ERROR,               hex(91))
def(ERR_DIVIDE_BY_ZERO,             hex(92))
def(ERR_IO_ERROR,                   hex(93))

comment Parse virtual machine (PVM) constants and instruction codes

def(PVM_MATCH,                      hex(00))
def(PVM_MATCH_RANGE,                hex(C0))
def(PVM_CALL,                       hex(D0))
def(PVM_JUMP,                       hex(D4))
def(PVM_BRANCH_IF,                  hex(D8))
def(PVM_RETURN,                     hex(F0))
def(PVM_GUARD,                      hex(F1))
def(PVM_SLURP,                      hex(F2))
def(PVM_FAIL,                       hex(FF))

comment Other constants

def(EOT, hex(80))
def(BUFFER_SIZE, 256)
def(PRIMARY_STACK_SIZE, 192)
def(OP_STACK_SIZE, 16)
def(STRING_EXTRA, 3)

comment Maximum line length we're willing to encode (leave 16 bytes at end for END statement in immediate mode)
def(MAX_LINE_LENGTH, 240)

comment Dispatch templates (4-bit packed metadata: bits 0-1 epilog, bits 2-3 prolog)

def(EPILOG_NONE,        0)
def(EPILOG_PUSH_FP,     hex(01))
def(EPILOG_PUSH_INT,    hex(02))
def(EPILOG_PUSH_STRING, hex(03))
def(PROLOG_NONE,        0)
def(PROLOG_POP_FP,      hex(04))
def(PROLOG_POP_INT,     hex(08))
def(PROLOG_POP_STRING,  hex(0C))

